version: 2

jobs:
 build:
   machine: true
   working_directory: ~/workspace

   steps:
     - checkout
     - run:
         name: Build docker image
         command: |
           docker login -u $DOCKER_LOGIN_ID -p $DOCKER_LOGIN_PASSWORD
           docker build --pull -t ${CIRCLE_USERNAME}/apache-proxy:latest .
     - run:
         name: Tagging
         command: |
           docker tag ${CIRCLE_USERNAME}/apache-proxy:latest ${CIRCLE_USERNAME}/apache-proxy:${CIRCLE_SHA1:0:6}
     - run:
         name: Push to docker hub
         command: |
           docker login -u $DOCKER_LOGIN_ID -p $DOCKER_LOGIN_PASSWORD
           docker push ${CIRCLE_USERNAME}/apache-proxy:${CIRCLE_SHA1:0:6}
           docker push ${CIRCLE_USERNAME}/apache-proxy:latest

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
